//mongo localhost:27042/sportDB backend/Models/addcategory.js

db.category.insertMany( [
    { name: "Athlétisme" },
    { name: "BasketBall" },
    { name: "Badminton" },
    { name: "Beach-Volley" },
    { name: "Biathlon" },
    { name: "Bobsleigh" },
    { name: "Bowling" },
    { name: "Boxe" },
    { name: "Canoë-kayak" },
    { name: "Canyonning" },
    { name: "Curling" },
    { name: "Equitation" },
    { name: "Escrime" },
    { name: "Football" },
    { name: "Football américain" },
    { name: "Futsal" },
    { name: "Gymnastique" },
    { name: "Handball" },
    { name: "Hockey sur glace" },
    { name: "Jorkyball" },
    { name: "Joute nautique" },
    { name: "Kin-Ball" },
    { name: "Luge" },
    { name: "Lutte" },
    { name: "Paintball" },
    { name: "Pancrace" },
    { name: "Parkour" },
    { name: "Patinage" },
    { name: "Plongée" },
    { name: "Rafting" },
    { name: "Rugby" },
    { name: "Saut à l'élastique" },
    { name: "Saut à ski" },
    { name: "Savate" },
    { name: "Skeleton" },
    { name: "Ski" },
    { name: "Ski alpin" },
    { name: "Ski de fond" },
    { name: "Ski nautique" },
    { name: "Snowboard" },
    { name: "Tennis" },
    { name: "Tennis de Table" },
    { name: "Torball" },
    { name: "Touch rugby" },
    { name: "Volley-Ball" },
 ] );